add Software I2C emulate to drive OLED
ExpressLRS/ExpressLRS pull request #1072
Opened 2021-11-08 08:09 UTC by kimman1

Hi dev, 
I'm adding I2C software emulate to driver OLED instead of SPI using 2 GPIO 32 and 32 
Tested on DIY E28 module 
Please help me to review and let me know if it have any issues

2021-11-08 21:07 UTC, cruwaller requested changes

2021-11-08 21:07 UTC, cruwaller commented on src/lib/OLED/OLED.cpp
> +    #if defined(USE_OLED_I2C) && defined(USE_SW_I2C)
No need to double check `USE_OLED_I2C`

2021-11-08 21:07 UTC, cruwaller commented on src/lib/OLED/OLED.cpp
> +#if defined(USE_OLED_SPI) || defined(USE_OLED_SPI_SMALL) || defined(USE_OLED_I2C) || defined(USE_SW_I2C_OLED) // This code will not be used if the hardware does not have a OLED display. Maybe a bette
`USE_OLED_I2C` is already required so no need to add `USE_SW_I2C_OLED`. 
This same applies to all similar cases.

2021-11-08 21:07 UTC, cruwaller commented on src/include/target/DIY_2400_TX_ESP32_SX1280_E28.h
> -#define USE_OLED_SPI
I would not change default value. Maybe OLED type into user defines for DIY purposes?

2021-11-09 04:01 UTC, pkendall64 commented on src/src/options.cpp
> +        "-DUSE_OLED_I2C_SW"
with a space at the end so other appended ones are space separated

2021-11-09 05:31 UTC, cruwaller requested changes

2021-11-09 05:31 UTC, cruwaller commented on src/lib/OLED/XBMStrings.h
> +#if defined(USE_OLED_SPI) || defined(USE_OLED_I2C) || defined(USE_SW_I2C_OLED)
defined(USE_SW_I2C_OLED) not needed. Please revert the file.

2021-11-09 05:31 UTC, cruwaller commented on src/lib/OLED/devOLED.cpp
> +#if defined(USE_OLED_SPI) || defined(USE_OLED_SPI_SMALL) || defined(USE_OLED_I2C)
Unnecessary change... please revert the file.

2021-11-09 07:35 UTC, pkendall64 commented on src/lib/OLED/XBMStrings.h
> +#if defined(USE_OLED_SPI) || defined(USE_OLED_I2C)
You should also revert the whitespace change so there are no changes to the file.

2021-11-09 08:46 UTC, cruwaller submitted a review, later dismissed

2021-11-09 11:53 UTC, FOG-Yamato approved these changes

2021-11-09 20:11 UTC, pkendall64 commented
I've asked kimman1 to try hardware I2C because that should work and this whole PR should not be necessary. We knoe that the I2C pins can be moved from the default because the `BETAFPV_900_TX_MICRO.h` uses non-default pins and (I assume) it works fine.

2021-11-10 02:56 UTC, kimman1 commented
> I've asked kimman1 to try hardware I2C because that should work and this whole PR should not be necessary. We knoe that the I2C pins can be moved from the default because the `BETAFPV_900_TX_MICRO.h` uses non-default pins and (I assume) it works fine.

I will try it ASAP

2021-11-10 19:33 UTC, pkendall64 commented
I tested this myself, The only change required is to define the pins
```cpp
#elif defined(USE_OLED_I2C)
#define GPIO_PIN_OLED_SDA       32
#define GPIO_PIN_OLED_SCK       33
#define GPIO_PIN_OLED_RST       U8X8_PIN_NONE
#endif
```
and tp replace the define to enable them to `USE_OLED_I2C` from `USE_OLED_SPI`

2021-11-11 08:11 UTC, pkendall64 commented on src/include/target/DIY_2400_TX_ESP32_SX1280_E28.h
> +#endif
So this change can be reverted.
Or perhaps changed to 
```cpp
#if !defined(USE_OLED_I2C)
#define USE_OLED_SPI
#endif
```

2021-11-11 08:11 UTC, pkendall64 commented on src/lib/OLED/OLED.cpp
> +#if defined(USE_OLED_SPI) || defined(USE_OLED_SPI_SMALL) || defined(USE_OLED_I2C)  // This code will not be used if the hardware does not have a OLED display. Maybe a better way to blacklist it in pl
This whole file can be reverted

2021-11-11 08:11 UTC, pkendall64 commented on src/lib/OLED/OLED.cpp
> +    #endif
revert

2021-11-11 08:11 UTC, pkendall64 commented on src/src/options.cpp
> +    #endif
revert

2021-11-11 08:11 UTC, pkendall64 commented on src/include/target/DIY_2400_TX_ESP32_SX1280_E28.h
> +#endif
These are the only changes required

2021-11-11 08:31 UTC, pkendall64 commented on src/lib/OLED/OLED.cpp
> +#endif
And the whitespace changes here can be reverted too

2021-11-11 08:34 UTC, pkendall64 commented on src/lib/OLED/OLED.cpp
> +#endif
you've got an extra endif here

2021-11-11 08:34 UTC, pkendall64 commented on src/user_defines.txt
> +
Remove the _SW

2021-11-11 21:28 UTC, cruwaller commented
Nice work!

@kimman1 I think you should remove all old commits by force pushing just the latest changes. 
That would keep commit history cleaner even for squashed commit.

2021-11-12 03:22 UTC, kimman1 commented
> Nice work!
> 
> @kimman1 I think you should remove all old commits by force pushing just the latest changes. That would keep commit history cleaner even for squashed commit.

Can you help me to remove it ?. I don't know how to remove

2021-11-12 21:10 UTC, pkendall64 commented
I made the squash changes for you @kimman1 and also renamed the PR.

2021-11-13 09:46 UTC, cruwaller commented
Thanks @pkendall64 !

2021-11-13 09:46 UTC, cruwaller approved these changes

2021-11-13 14:42 UTC, FOG-Yamato approved these changes

2021-11-16 00:42 UTC, merged

2021-11-17 17:42 UTC, CapnBry commented
Can someone explain this to me? 🤔
```
#define USE_OLED_I2C
#if !defined(USE_OLED_I2C)
#define USE_OLED_SPI
#endif
```

2021-11-17 17:55 UTC, pkendall64 commented
The top define should not be in the header file damn it! That should be a define that a user makes in `super_defines.h`. If they are hacking hardware they should be good enough the hack the code.