[MENU/ JOYSTICK] adding fuzz value array
ExpressLRS/ExpressLRS pull request #1294
Opened 2022-01-20 14:19 UTC by brandonrc

Replacing the single fuzz value for an array of fuzz values. 

Jumper did not do a linear resistor ladder so the values are different based on position. The solution is to check each value and see what is the smallest distance between the next value and divide that in half. This will avoid collisions. 

Tested on ghost tx and ghost tx lite.

2022-01-20 15:07 UTC, CapnBry requested changes
I've listed a lot of things as "should be static" but I'm not sure why these aren't private functions on the FiveWayButton class? And can you remove these unused defines?
```
#define UP    0;
#define DOWN  1;
#define LEFT  2;
#define RIGHT 3;
#define ENTER 4;
#define IDLE  5;
```

2022-01-20 22:11 UTC, brandonrc commented on src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
> +            if(joyAdcValues[i] == sortedJoyAdcValues [j] ){
That is my bad.. it was a quick proof of concept this morning before I ran to work :)

2022-01-20 22:43 UTC, brandonrc commented on src/lib/SCREEN/FiveWayButton/FiveWayButton.cpp
> +int16_t fuzzValues[] = {0,0,0,0,0,0};
What do you mean by `helpers.h`. 

Like move some of the code to a the helpers.h file and include that here?

2022-01-22 19:38 UTC, CapnBry commented
* I've moved all the code into the FiveWayButton class instead of being in the global namespace
* Replaced sorting the array to calculate the fuzz values with a simple search for the closest neighbor
* Replaced `handle() + getKeyState()` with just a single `update()` that returns keyState
* Added compiler errors for if GPIO_PIN_JOYSTICK is defined and JOY_ADC_VALUES is not and vice versa
* Changed KEY_DEBOUNCE_TIME to actually debounce the press event. I'm not sure what the old code was doing, preventing a second keypress within a certain amount of time?

Reduced code size by 440 bytes and RAM by 16 bytes for analog 5ways.

Tested on Namimno Flash OLED and Axis Thor.

2022-01-22 19:47 UTC, CapnBry approved these changes

2022-01-22 20:01 UTC, schugabe approved these changes
Tested on the aion nano module that was the reason for the change.

2022-01-23 04:04 UTC, brandonrc commented
Tested on (and works):
Ghost TX Full
Ghost TX Lite
BetaFPV Micro 2.4 1000mW
NamimnoRC Flash 2.4 OLED

2022-01-23 04:04 UTC, merged