Serial pin checking
ExpressLRS/ExpressLRS pull request #1335
Opened 2022-01-24 20:33 UTC by pkendall64

# Problem
My AION Nano was failing with the latest code.
It seems that using `HardwareSerial LoggingBackpack(2);` is a problem with the default UART0 pins if we've not also defined `NO_GLOBAL_SERIAL` in the PICO-D4!

# Symptom
When flashed my AION Nano looked completely dead, no lights, OLED and even nothing on the serial other than the standard ESP boot message.

# Solution
- Always define `NO_GLOBAL_SERIAL` on ESP32 devices, so we have to be explicit in the pins we use
- Add some extra checks to ensure we do not have conflicts or try to use features that are not supported because of undefined pins

2022-01-24 20:45 UTC, CapnBry requested changes
I also ran into this this morning, where the SIYI FM30 didn't work after compiling either. We can't use "HardwareSerial" as the type reference because the FM30 uses USBSerial for its LoggingBackpack. The common parent class is Stream, which is a subclass of Print, so I think we should change it to Stream as the reference so it supports everything.

I think this also needs more cleanup work too, such as making MSP::sendPacket static since it only operates on the passed parameters, which then means you can remove the extern msp reference from devVTX as well, since a class instance would not be required.

There will be some other changes needed for FM30 as well, but I want your input on the LoggingBackpack type and if you think Stream is acceptable.

2022-01-24 21:00 UTC, pkendall64 commented
Yes I agree that Stream is the right interface to use for this. I'll update the PR shortly.

2022-01-24 23:57 UTC, pkendall64 commented
> I also ran into this this morning, where the SIYI FM30 didn't work after compiling either. We can't use "HardwareSerial" as the type reference because the FM30 uses USBSerial for its LoggingBackpack. The common parent class is Stream, which is a subclass of Print, so I think we should change it to Stream as the reference so it supports everything.

I made the change, not sure if it's ok as I don't have an FM30

> I think this also needs more cleanup work too, such as making MSP::sendPacket static since it only operates on the passed parameters, which then means you can remove the extern msp reference from devVTX as well, since a class instance would not be required.

Change made

2022-01-25 19:46 UTC, schugabe approved these changes

2022-01-25 22:49 UTC, CapnBry approved these changes
Thank you for cleaning up my mess! Looks good to me now. Tested on FM30, EP2, Aion TX.

2022-01-25 22:50 UTC, pkendall64 reviewed
Your changes look good @CapnBry

2022-01-25 23:02 UTC, merged