porting st7735 tft lcd to diy2400 e28 target
ExpressLRS/ExpressLRS pull request #1357
Opened 2022-01-26 15:01 UTC by gcrisis

I find that st7735 tft lcd has some  different types.They have different setup,like "TFT_RGB_ORDER" and "ST7735_GREENTAB160x80" or "ST7735_REDTAB160x80";
If one buy a lcd not match the default setup,the screen will not display graphics correctly.
I don't know how to make a one for all setup,so I keep origin setup.

https://user-images.githubusercontent.com/13515569/151187829-c8885b61-ea05-477e-b0e7-d82e638d60e7.mp4

2022-01-27 14:07 UTC, FOG-Yamato requested changes
I would also make sure that the menus look okay as this was never used outside of the Axis Thor target.

2022-01-27 14:07 UTC, FOG-Yamato commented on src/include/target/DIY_2400_TX_ESP32_SX1280_E28.h
> +#endif
This is not the recommended way to wire up a 5 way joystick, the better option is to use a voltage divider on a single ADC pin.

2022-01-27 14:07 UTC, FOG-Yamato commented on src/include/target/DIY_2400_TX_ESP32_SX1280_E28.h
> +#define TARGET_DIY_2400_TX_ESP32_SX1280_E28
This is already defined in the PlatformIO targets, doesn't need to be present here as well.

2022-01-27 14:07 UTC, FOG-Yamato commented on src/lib/SCREEN/TFT/TFT_eSPI_User_Setup.h
> +#ifdef HAS_TFT_SCREEN
It would be better if it encompassed all the defines in this header file.

2022-03-20 21:24 UTC, JyeSmith commented
@gcrisis looks like this needs a rebase and address some comments.  Any updates?

2022-03-22 08:55 UTC, closed without merging