Namimno PA target
ExpressLRS/ExpressLRS pull request #1519
Opened 2022-04-11 07:07 UTC by SunjunKim

2022-04-11 08:47 UTC, pkendall64 approved these changes

2022-04-11 11:39 UTC, StonedDawg approved these changes

2022-04-11 11:49 UTC, StonedDawg requested changes

2022-04-11 11:49 UTC, StonedDawg commented on src/include/target/NamimnoRC_FLASH_2400_RX_ESP8285_PA.h
> +#define POWER_OUTPUT_VALUES     {-15, -10, -7, 3} //has PA, use Power array
2.3.x doesnt have adjustable power yet, just use fixed output power with the current max (3) and min/max,default doesn't have to be defined too.

2022-04-12 00:20 UTC, FOG-Yamato approved these changes

2022-04-12 09:41 UTC, StonedDawg approved these changes

2022-04-12 09:42 UTC, merged