fix binding after OTA change
ExpressLRS/ExpressLRS pull request #1656
Opened 2022-06-28 08:47 UTC by JyeSmith

Fixes the UID bytes that were not being set correctly during manual binding.

The tx was also not exiting TLM 1:2 mode after binding.  Im not sure if this is the correct way to fix it, but Ive added a MspSender.ResetState().

2022-06-28 09:01 UTC, pkendall64 approved these changes
The binding part is the correct fix. Not sure about the reset, but if it works 🤷‍♂️

2022-06-28 21:18 UTC, CapnBry requested changes

2022-06-29 09:28 UTC, JyeSmith commented on src/src/tx_main.cpp
> +  MspSender.ResetState();
I didnt see a problem with the rx scoreboard but have chucked in MspReceiver.ResetState just in case.

2022-06-29 11:42 UTC, CapnBry commented on src/src/tx_main.cpp
> +  MspSender.ResetState();
It wouldn't be a problem **if the RX's Confirm happened to be 0** (which is the case on a fresh plugin). If it already had a connection, prior to the binding, then the confirm could be 1 on the RX, which means that doing the Reset on the TX would force them out of sync. The only way to make sure they're the same regardless of the start conditions is to reset on both sides when leaving Bind.

2022-06-29 11:42 UTC, CapnBry approved these changes

2022-06-29 11:45 UTC, merged