Module Configuration Import/Export
ExpressLRS/ExpressLRS pull request #1943
Opened 2022-11-13 03:25 UTC by pkendall64

# Problem
I've got my models all setup in my ELRS module (all 64 of them 😉), and I just got a new module/radio and I don't want to go through the hassle of setting them all up again!
Help me out devs!

# Solution
We got you back bro!
On the "Options" tab we've added a new section, "Import/Export", which allow you to save your module config, along with all your models to a JSON file. This file can then be loaded into another module.

![Screenshot 2022-11-13 at 4 08 40 PM](https://user-images.githubusercontent.com/512740/201503771-14c1234f-c9e6-4aea-a074-38f2aa3e9ca9.png)

The information saved in the file is as follows:
- Fan mode
- Power fan threshold
- Motion mode
- VTX admin
   - Band
   - Channel
   - Pitmode
   - Power
- Backpack
   - DVR start delay
   - DVR stop delay
   - DVR aux channel

All 64 models:
- Packet rate
- Telemetry ratio
- Switch mode
- Power settings
   - Max power
   - Dynamic power
   - Boost channel
- Model match enabled flag
- TX antenna

# Extra
Converted the link to reset options to a button as well, so it's consistent.

2022-11-24 01:07 UTC, JyeSmith commented
Could this be extended to be a generic clone function e,g, also include bind phrase, wifi details etc?

2022-11-24 01:22 UTC, pkendall64 commented
> Could this be extended to be a generic clone function e,g, also include bind phrase, wifi details etc?

Yes, we could add that too. We'd probably then want the user to select which items to export and/or import i.e. models and options or just one.

2022-12-17 02:38 UTC, deadbytefpv requested changes
Tested importing config from a NamimnoRC Flash OLED TX into an EMAX 2.4G OLED TX, works great.

Tested importing config from a NamimnoRC Flash OLED TX into an EMAX 900 OLED TX, the import works, but because it's a 2.4GHz TX config being saved into a 900MHz TX, the parameters will not always line up. See attached screengrab.
![IMG_0304](https://user-images.githubusercontent.com/83231715/208219758-608e6356-5365-4e2b-a9f3-b31c2817ca41.JPG)

2022-12-17 02:38 UTC, deadbytefpv commented on src/html/scan.js
> +            message: 'An error occurred while upload model configuration file'
An error occurred while uploading model configuration file.

2022-12-17 05:52 UTC, JyeSmith reviewed
Tested with the Emax 900 OLED.  Changed all the things and exported the settings.  Then changed everything and imported the setting which successfully restored the original settings.

2022-12-17 05:52 UTC, JyeSmith approved these changes

2022-12-17 07:23 UTC, deadbytefpv approved these changes

2022-12-17 21:28 UTC, merged