Cleanup of the CRSF header and code
ExpressLRS/ExpressLRS pull request #2320
Opened 2023-07-23 20:48 UTC by pkendall64

This is a maintenance PR, which just shuffles things around to simplify the ifdefs to make the code a little easier to follow.

2023-07-26 08:55 UTC, JyeSmith approved these changes

2023-08-21 16:09 UTC, CapnBry requested changes

2023-08-21 18:32 UTC, pkendall64 commented on src/lib/CRSF/CRSF.cpp
> -#elif CRSF_TX_MODULE_STM32
Good call

2023-08-21 18:37 UTC, pkendall64 commented on src/lib/CRSF/CRSF.cpp
> -    #if defined(PLATFORM_ESP32)
Why don't we always call `devicesTriggerEvent` when the arm state changes? It's only setting a flag for the main loop!
I'd have to make that function `ICACHE_RAM_ATTR` too.

2023-08-21 19:26 UTC, pkendall64 commented on src/lib/CRSF/CRSF.cpp
> -    #if defined(PLATFORM_ESP32)
Move the ifdef back.

2023-08-21 19:35 UTC, CapnBry commented on src/lib/CRSF/CRSF.cpp
> -    #if defined(PLATFORM_ESP32)
Dangit! I was hoping you'd do some magic instead 🎇

2023-08-21 19:35 UTC, CapnBry approved these changes

2023-08-21 19:39 UTC, merged