Configurable I2C pins for PWM capable (ESP32) receivers
ExpressLRS/ExpressLRS pull request #2425
Opened 2023-09-30 21:28 UTC by pkendall64

This allows the user to select which pins to use as I2C pins (`I2C SDA` and `I2C SCL` in Lua).
Also this allows a target to nominate pins as I2C pins, so only those pins are able to be selected. e.g. the BetaFPV Super-P receivers which have a separate connector for I2C.

2023-10-07 19:35 UTC, CapnBry requested changes
Tested with my recommended changes to the lua option generator / default config.

* BetaFPV SuperP with defining the target SDA/SCL pins - PASS can only make those pins I2C
* BetaFPV SuperP without defining the target SDA/SCL pins - FAIL can make any pins I2C, but they do not function. See changes to `setupWire()` below. PASS after changes
* RadioMaster ER8 changing two pins to I2C - PASS (after changes) can make any pins I2C
* PWMP~~6~~ - FAIL changes needed. Offers DShot option, pin function not correct, ~~I2C still does not work after changes (does not detect any devices)~~ EDIT: I am an idiot that can not count past 5. This is a 5 pin PWMP not 6, works after assigning the correct pins, but needs DShot removed still.

For testing I2C I connected a BME280 and added a detect the end of to setupWire():
```cpp
        for(uint8_t address = 1; address < 127; ++address)
        {
            Wire.beginTransmission(address);
            if (Wire.endTransmission() == 0)
                DBGLN("I2C 0x%x", address);
        }
```

Not sure why the ESP8266 does not find any I2C devices. Have you tested any ESP with I2C with this PR? Maybe my Matek P6 has the wrong pullup values, I will check with logic analyzer.

2023-10-08 00:05 UTC, CapnBry approved these changes
Oh wow, you even took out the DShot define. [my man! meme] For a moment I thought something was broken because the SCL showed up blank on the Lua, but then I reviewed the diff and did a little dance.

Retested all the above cases, checked via Lua and webui, everything is perfect and the new pin feature badges look great!

EDIT: webui screenshot for those who aren't fortunate enough to have seen how nice the Features badges look
![image](https://github.com/ExpressLRS/ExpressLRS/assets/677183/f1357c74-fcab-4490-9828-45e36995098a)

2023-10-08 18:23 UTC, CapnBry commented
Just for good measure, and because I put it on my desk and intended to test it as well, I tested with a RadioMaster 6ch Vario RX which has dedicated, non-shared I2C. Performed correctly, no pins show the feature for I2C and the Lua does not allow I2C to be selected for use on the PWM pins.

2023-11-04 22:03 UTC, JyeSmith approved these changes

2023-11-04 22:03 UTC, merged