Pin AsyncTCP to specific version
ExpressLRS/ExpressLRS pull request #2511
Opened 2023-12-22 18:23 UTC by pkendall64

This fixes the build because an update to an unmanaged transitive dependency broke the build!

2023-12-22 22:44 UTC, JyeSmith approved these changes

2023-12-26 15:03 UTC, CapnBry requested changes
Change comment to include useful info?
```
esphome/AsyncTCP-esphome @ 2.0.1 # 2.1.0 changes function signatures to support IPV6 and is incompatible
```
Same goes for the backpack PR 😊

2023-12-26 18:33 UTC, pkendall64 commented
> Change comment to include useful info?
> 
> ```
> esphome/AsyncTCP-esphome @ 2.0.1 # 2.1.0 changes function signatures to support IPV6 and is incompatible
> ```
> 

It's not that the signatures are different, it's that the tagged version just doesn't even compile. They've completely f**ked it up!
check https://github.com/esphome/AsyncTCP/blob/ab9b7d4a22d2bbc15ed81ef4e7a0130440ad7ab3/src/AsyncTCP.cpp#L753 and https://github.com/esphome/AsyncTCP/blob/ab9b7d4a22d2bbc15ed81ef4e7a0130440ad7ab3/src/AsyncTCP.cpp#L1020

I think their merge just failed.

2023-12-26 20:01 UTC, CapnBry approved these changes
Argh you're right I was reading the wrong thing 😞

2023-12-26 20:11 UTC, merged