VTXAdmin PitMode On using YAW channel to trigger
ExpressLRS/ExpressLRS pull request #2740
Opened 2024-05-27 13:30 UTC by CapnBry

If VTX Admim has PitMode set to ON, the YAW channel is being used to trigger it on and off. The issue is just this code, where only `PIDMODE_OFF` is considered to not be "Pit mode on a switch", so `PITMODE_ON` is interpreted as "pit mode on channel 4"
```patch
-    if (config.GetVtxPitmode() == PITMODE_OFF)
+    if (config.GetVtxPitmode() <= PITMODE_ON)
```

I also added comments for what the bytes being added are, and combined the code for checking PITMODE_OFF/PITMODE_ON into one place instead of having two if statements in different places.

### Testing
* To reproduce bug (on any ELRS version since VTX Admin was added): Enable VTX Admin e.g. Band=R Channel=1 Power=1 (**must be set**!) PitMode=ON. Send VTX. Hold Yaw stick (or ch4, whatever you have on that) left, hold Yaw stick right Pit mode will be turning on and off

2024-05-28 04:46 UTC, Reeseb1222 requested changes
Run

2024-05-28 05:17 UTC, pkendall64 approved these changes

2024-06-01 07:03 UTC, JyeSmith approved these changes
Sounded like a cool feature.

2024-06-01 07:03 UTC, merged

2024-06-01 11:02 UTC, Reeseb1222 commented
Love it