Decrease mav rx to ardu baud
ExpressLRS/ExpressLRS pull request #2802
Opened 2024-06-20 00:44 UTC by JyeSmith

As suggested by MT, we appear to be dropping bytes on the wire from the FC.  As a result we drop about 1% of the packets because they never actually make it to the Rx.

Reducing the baud looks to eliminate (or greatly reduce) the issue.

![image](https://github.com/ExpressLRS/ExpressLRS/assets/14170229/4aa3ea65-e327-482d-b424-53043d13f263)

2024-06-21 01:21 UTC, JyeSmith commented
Added a limit to the max packet rate.  Prof Wez mentioned that at 1000Hz (500Hz RC rate) we will be saturating the TX line.  Confirmed to be correct and at a more sensible 250Hz TX line looks much better.

The bottom RC trace indicates when RC packet are sent from the Rx to FC.
![image](https://github.com/ExpressLRS/ExpressLRS/assets/14170229/72cb14d6-a59f-4dac-914e-d8082fd5b1b9)

2024-06-23 00:44 UTC, wvarty commented on src/src/rx-serial/SerialMavlink.cpp
> +    return MIN_PACKET_INTERVAL;
This method of rate limiting causes major impacts to TQTY on ESP8285 receivers. Need to use a "simpler" approach to check if we should forward the pkt out or not.

2024-06-23 00:45 UTC, wvarty requested changes
Rate limiting needs work

2024-08-11 06:13 UTC, wvarty commented
Retested after latest changes to the rate limiting.

460k baud after 10mins:
![3 x x 460k](https://github.com/user-attachments/assets/2fb32436-12ab-4100-a826-9315bce43ef6)

230k baud after 10mins:
![230k](https://github.com/user-attachments/assets/70cea260-6df1-42f4-998a-04dced2ec3bf)

Seems like a negligible difference in dropped pkt counts... not worth changing?

2024-08-11 06:27 UTC, closed without merging