Correct diversity rx tlm radio selection for non LBT
ExpressLRS/ExpressLRS pull request #2812
Opened 2024-06-26 20:39 UTC by JyeSmith

2024-06-26 21:27 UTC, mha1 requested changes

2024-06-26 21:27 UTC, mha1 commented on src/src/rx_main.cpp
> +    transmittingRadio &= ChannelIsClear(transmittingRadio);   // weed out the radio(s) if channel in use
The LBT `#ifdef` section should be placed before the `if (!geminiMode && transmittingRadio == SX12XX_Radio_All)` section.

As it is now Radio_ALL would be reduced to Radio_1 or Radio_2 before CCA with the opportunity for CCA to further reduce it to Radio_NONE. Changing the order will first do CCA on two radios increasing the chances of at least one radio surviving. If both radios survived CCA the following `if (!geminiMode && transmittingRadio == SX12XX_Radio_All)` will pick the better one just like ISM does.

2024-06-27 08:08 UTC, pkendall64 approved these changes

2024-06-27 10:36 UTC, mha1 approved these changes
lgtm, no obvious side effects.

2024-06-27 10:36 UTC, merged