Remove Serial1 MAVLink check; MAVLink is supported on Serial0 only
ExpressLRS/ExpressLRS pull request #2979
Opened 2024-10-11 15:57 UTC by MUSTARDTIGERFPV

![image](https://github.com/user-attachments/assets/d917f6c3-9d02-4df3-b861-a8cd20394e4e)

2024-10-11 16:48 UTC, mha1 requested changes
You could further reduce this by deleting lines 536 and 537 and change the following if statement to be `if (config.GetSerialProtocol() == PROTOCOL_MAVLINK)`

2024-10-12 01:09 UTC, JyeSmith approved these changes

2024-10-20 00:57 UTC, wvarty approved these changes

2024-10-20 19:55 UTC, pkendall64 requested changes

2024-10-20 19:55 UTC, pkendall64 commented on src/lib/LUA/rx_devLUA.cpp
>    if (hasMavlink)
Actually, these should always be registered i.e. no if block.
And at the end of event loop the fields should be shown/hidden depending on the protocol selected, similar to the backpack options on the TX side of things.

2024-10-20 21:23 UTC, pkendall64 approved these changes

2024-10-21 18:11 UTC, mha1 approved these changes

2024-10-21 18:12 UTC, merged