GPS beacon mode
ExpressLRS/ExpressLRS pull request #3020
Opened 2024-11-05 10:51 UTC by Yury-MonZon

Hello everyone! 

I've developed a custom beacon mode for ELRS and am interested in contributing it to the ELRS project.

Here's what it currently does:

- Saves the last valid GPS coordinates (based on satellite count) received by the RX from the FC.
- If the ELRS link goes down, the RX waits 5 minutes, then begins broadcasting GPS coordinates every 30 seconds in slow LoRa mode, maximizing range and sensitivity. It also forces the RX to maximum power and cycles antennas (if multiple are present). Transmission stops if the ELRS link is re-established.
- Adds a screen in the radio's LUA script to display received beacon data.
![image](https://github.com/user-attachments/assets/ad8540dd-0461-40e0-a512-e3845539ca34)
- If the RX doesn’t receive GPS data from the FC for 1 minute (e.g., FC is off/disconnected, but RX has external power), it sends the last saved GPS coordinates over the ELRS link every 10 seconds. While outdated, this information can be helpful for locating the aircraft. It won’t be used for navigation, but it will display in the LUA scripts on radio screen.
- Disables Wi-Fi mode on the RX after a 3-minute timeout, keeping the device available. If Wi-Fi activity is detected, the timer resets.

This has been tested with a Jumper T-20, my custom ESP32-based 868 TX, Radiomaster BR3 RX, and my ESP8285 RX running ExpressLRS 3.4.3 master. Currently, it only works with SX127X chips, and the beacon frequency is hardcoded.

2024-11-06 04:06 UTC, pkendall64 commented on src/user_defines.txt
There should be no changes to this file

2024-11-06 08:22 UTC, pkendall64 requested changes
Let's also make this work for all radio types.

2024-11-06 08:22 UTC, pkendall64 commented on src/lib/LUA/tx_devLUA.cpp
> +        rebootTime = millis() + 400;
You don't need the #if and #else part as we're removing STM32 in the master branch.

2024-11-06 08:22 UTC, pkendall64 commented on src/src/rx_main.cpp
> +#define BeaconFrequency     868750000
How about using the `freq_center` from the `FHSSconfig` structure, or maybe add another element to the end with the beacon frequency. That way these defines are not needed.

2024-11-06 22:02 UTC, JyeSmith commented
I like the idea but have a few comments.

- This needs to be available for all transceivers.  Targeting just the SX1276 is particularly bad going forward because we will see it be replaced by the LR1121.
- I think this could be made into a Device and utilise the Timeout/Events for the activation periods.  This should help organise the code a bit more.
- The Rx must go back into rxmode after sending a beacon packet.  What happens if this is a long range flight and the beacon kicks in after FS and RTH?  Sometimes the link may not return for a long period and if beacon mode triggers then control of the craft can not be restored.
- I agree with using the freq_center.
- We need to be mindful of adding too much to Lua.  My next comment helps address this.

- The beacon packet will have the best chance of being received if it is as small as possible.  We only want to send the bare minimum information to get the user close enough to the craft and restore a connection, or minimise the search area.  Sending only long and lat to 4 decimal places will get the user within ~11m.  This should be enough to find the craft.  Anything else in the packet will only increase the chances of the packet not being received successfully.  The CRC8 I think is fine, but it would also be nice to process a pkt with a failed CRC.  The info can still be displayed but with a * or some indicator it failed CRC.  The data may not be trust worthy but the user now knows they are getting close.

Sorry for the large brain dump.

2024-11-08 03:05 UTC, pkendall64 commented on src/lib/LUA/tx_devLUA.cpp
> +        rebootTime = millis() + 400;
It is fully removed, we're just cleaning up some of the left over ifdef's

2025-03-20 11:05 UTC, closed without merging