Ghost bootloader
ExpressLRS/ExpressLRS pull request #354
Opened 2021-02-19 02:37 UTC by brandonrc

Working on a bootloader for ghost tx module.

2021-02-19 02:37 UTC, brandonrc commented
@peho-nordic Need some help!

2021-02-19 02:39 UTC, brandonrc commented
@cruwaller need some help with the bootloader. 

Thanks, 

Currently I am not getting into the ELRS firmware at boot. Just gets stuck.

2021-02-19 05:43 UTC, cruwaller requested changes

2021-02-19 05:43 UTC, cruwaller commented on src/bootloader/src/Src/uart.c
> +    case GPIO('A', 10):
STM32F3xx only.

2021-02-19 05:43 UTC, cruwaller commented on src/bootloader/src/Src/uart.c
> +      USART1->CR2 |= USART_CR2_RXINV | USART_CR2_TXINV | USART_CR2_SWAP; //inv
Write there bits into `UART_CR_RX` and `UART_CR_TX` variables.

2021-02-19 05:43 UTC, cruwaller commented on src/bootloader/src/platformio.ini
> +    -D UART_RX_PIN="A,10"
Remove RX definition.

2021-02-19 05:43 UTC, cruwaller commented on src/bootloader/src/Src/uart.c
> +      USART1->CR2 |= USART_CR2_RXINV | USART_CR2_TXINV | USART_CR2_SWAP; //inv
And `USART_CR2_SWAP` if TX pins is physical uart rx pin (e.g PA10).

2021-03-01 07:53 UTC, peho-nordic approved these changes
This bootloader is tested to work. Thanks @brandonrc !

2021-03-01 07:57 UTC, cruwaller approved these changes

2021-03-03 12:42 UTC, merged