Update README.md
ExpressLRS/ExpressLRS pull request #404
Opened 2021-03-24 14:18 UTC by brandonrc

Added updates for latest 2.4ghz hardware support and added a range test for the 2.4ghz DIY module.

2021-03-24 14:43 UTC, SpencerGraffunder commented
Suggestions:
remove the word "support" in line 24.
it's unclear in the 'rf noise' section whether other 900MHz RC control systems will interfere with 900MHz ELRS.
since the hardware compatibility table has 2.4ghz stuff already, the 'Where can I get 2.4GHz if I cannot solder?' seems redundant.

2021-03-24 15:19 UTC, brandonrc commented
@SpencerGraffunder I think one big issue I have seen on Facebook and even in our discord is this misconception that you have to build your own 2.4ghz stuff. 

Like the news has not gotten out that we have so many other options than DIY 2.4 ghz TX's... so many may be a stretch but yea. 

I have to constantly respond and help educate people and they end up saying why is the github README so out of date 🤷‍♂️ 

@AlessandroAU some feed back on the Where can I get 2.4GHz if I cannot solder? Have you also noticed people say there are no options for 2.4 outside of building your own?

2021-03-25 07:31 UTC, cruwaller requested changes

2021-03-25 07:31 UTC, cruwaller commented on README.md
> +|RX | FM30 Mini | Development | In STlink initial flash, betaflight passthrough update
Add space before `RX` and `|` to EOL.

2021-03-25 07:31 UTC, cruwaller commented on README.md
> +## Should I use 2.4ghz or 915/868mhz?
Align casing ( `ghz -> GHz` and `mhz` to `MHz`) and use it also later (not only 2.4 :) )

2021-03-25 07:31 UTC, cruwaller commented on README.md
> +## Should I use 2.4ghz or 915/868mhz?
And `hz` to `Hz`

2021-05-06 17:43 UTC, CapnBry commented
PR is obsolete now and I've integrated some of this text into the wiki. Closing after discussion with Brandon.

2021-05-06 17:43 UTC, closed without merging