safeguard againts LUA and module mismatch
ExpressLRS/ExpressLRS pull request #406
Opened 2021-03-24 18:59 UTC by StonedDawg

add ERROR screen and version info when LUA version and TX module version is not compatible to safeguard people from using the wrong LUA script and possibly enter wrong parameters.

2021-03-25 07:38 UTC, cruwaller requested changes
Thanks! 
This is good improvement.

2021-03-25 07:38 UTC, cruwaller commented on src/lua/ELRS.lua
> +                    tx_lua_version = data[12];
Fix the code indentation.

2021-03-25 07:38 UTC, cruwaller commented on src/lua/ELRS.lua
> +    yOffset = radio_data.yOffset_val
indentation

2021-03-25 09:19 UTC, StonedDawg commented
@cruwaller some parts of the code's indentation are spaces, and some parts are tabs, would you like me to change them to tabs?

2021-03-25 09:33 UTC, StonedDawg commented
> Thanks!
> This is good improvement.

thanks! all fixed..

2021-03-25 12:56 UTC, cruwaller approved these changes

2021-03-25 21:42 UTC, CapnBry commented
I just tested this on my develop branch and it works and is a good idea. I have two issues with it though:
* The updated lua running against an old TX that doesn't put out the version number reports "Update ELRS.lua to v.0(current v.3)". Maybe update refreshLCD() to point to the right direction. `if (tx_lua_version < version) then print("Update TX") else print("Update ELRS.lua") end` like that but prettier.
* If someone updates their TX and RX and heads out to the field without updating the LUA they're now 100% fully dead in the water when it comes to changing even the most basic ELRS parameters. Wouldn't it be better to gracefully degrade somehow? I could see this being a giant gotcha for something so active in development. Maybe have a minimum supported TX version and just lock out functionality based on tx_lua_version vs version. If they don't match draw a big inverse bar letting the user know which should be upgraded. I don't want the lua to be full of compatibility hacks but the way it is now means a dev just changing the version number locks everyone out and this is something that could be forgotten.

Pedantically, I'd also suggest renaming version to VERSION like it is a const/define so it is less ambiguous, or even LUA_PROTO_VERSION. Visually, maybe drop the decimal in the version number display too. v.0? v.3? why. Just v3

Note that I am not a developer so maybe take these with a grain of salt.

2021-03-26 05:00 UTC, StonedDawg commented
> I just tested this on my develop branch and it works and is a good idea. I have two issues with it though:
> 
> * The updated lua running against an old TX that doesn't put out the version number reports "Update ELRS.lua to v.0(current v.3)". Maybe update refreshLCD() to point to the right direction. `if (tx_lua_version < version) then print("Update TX") else print("Update ELRS.lua") end` like that but prettier.
> * If someone updates their TX and RX and heads out to the field without updating the LUA they're now 100% fully dead in the water when it comes to changing even the most basic ELRS parameters. Wouldn't it be better to gracefully degrade somehow? I could see this being a giant gotcha for something so active in development. Maybe have a minimum supported TX version and just lock out functionality based on tx_lua_version vs version. If they don't match draw a big inverse bar letting the user know which should be upgraded. I don't want the lua to be full of compatibility hacks but the way it is now means a dev just changing the version number locks everyone out and this is something that could be forgotten.
> 
> Pedantically, I'd also suggest renaming version to VERSION like it is a const/define so it is less ambiguous, or even LUA_PROTO_VERSION. Visually, maybe drop the decimal in the version number display too. v.0? v.3? why. Just v3
> 
> Note that I am not a developer so maybe take these with a grain of salt.

hmm with the 1st issue, I think displaying its version is kinda important and might help in-the-field LUA matching between multiple firmwares (if elrs.lua has been saved in handset as elrsv1.lua, elrsv2.lua), it might help testing multiple PR on site. although words selection is also up to devs, I will change to fit the best outcome.

with the 2nd issue, I can think of another way, which is with "OK" to confirm and keep using LUA as it is even outdated. since the UART byte length between v2 and v3 is different, LUA would only shows "???", I can make a workaround to adjust it but then Im not sure if it would be considered as "neat" for the codes to do that... anyway its up to the devs? I will change to get the best outcome.

2021-03-26 11:17 UTC, CapnBry commented
> hmm with the 1st issue, I think displaying its version is kinda important and might help in-the-field LUA matching between multiple firmwares (if elrs.lua has been saved in handset as elrsv1.lua, elrsv2.lua), it

Oh for sure yeah. I didn't type the whole thing out but I agree that showing the version number is important. My only complaint is that the way it is now always blames the LUA for being out of date even if it is the TX that is out of date.

2021-03-26 11:40 UTC, StonedDawg commented
@CapnBry ahhh got it, how about we use the word "match" instead of update?

2021-03-26 12:03 UTC, CapnBry commented
I was thinking something like this general idea
```
        lcd.drawText(lOffset, (radio_data.yOffset*2), "!!! VERSION MISMATCH !!!", INVERS)
        if (tx_lua_version > version) then
            lcd.drawText(lOffset, (radio_data.yOffset*3), "Update ELRS.lua", INVERS)
        else
            lcd.drawText(lOffset, (radio_data.yOffset*3), "Update TX module", INVERS)
        lcd.drawText(lOffset, (radio_data.yOffset*4), "LUA v"..version..", TX v"..tx_lua_version, INVERS)
```

2021-03-26 23:24 UTC, JyeSmith commented
@StonedDawg this is good to merge when you are ready 👍 

I am happy either way with the wording and have a feeling it may change again once users start seeing the message.

2021-03-26 23:24 UTC, JyeSmith approved these changes

2021-03-27 02:53 UTC, StonedDawg commented
@JyeSmith ok, I will changes words and add force use

2021-03-27 11:56 UTC, StonedDawg commented
@JyeSmith ok its ready, it can be forced backward, but not to v01 and v02 because of different packet length, it will stuck on connecting when it happened

2021-03-27 13:54 UTC, StonedDawg commented
> @JyeSmith ok its ready, it can be forced backward, but not to v01 and v02 because of different packet length, it will stuck on connecting when it happened

force use now will not check data length, this will be backward compatible with v02 but still not with v01 (v01 data value is out of range).

2021-03-27 23:59 UTC, merged