Spam sync packets on rf param change
ExpressLRS/ExpressLRS pull request #498
Opened 2021-04-20 04:20 UTC by AlessandroAU

I'm not very happy with how the logic works and it feels ugly so please suggest improvements.

Basically, when a RFparam is changed it will send 5 sync packets to the RX before doing the change, the RX will also hop to a different rfmode if needed when it gets these packets. This makes switching rates super fast and allows you to change rates even with -LOCK_ON_FIRST_CONNECTION enabled.

2021-04-20 07:07 UTC, JyeSmith requested changes

2021-04-20 07:08 UTC, JyeSmith commented
So nice.  Once this is merged we can remove LOCK_ON_FIRST_CONNECTION.

2021-04-20 23:03 UTC, CapnBry commented
Just to keep everyone in the loop where we are on this, there's a problem on STM32 targets which use internal flash to emulate EEPROM. When saving the configuration, interrupts stop firing and the TX stops updating the NonceTX properly during the ~30ms write operation. By the time it comes back, the RX and the TX are generally out of sync, hopping to different frequencies and only getting enough packets through for the RX to think the connection is still up so it never resyncs.

I'm not sure how to work around this. The only option is to move the timer ISR to RAM, along with the vector table to prevent accessing flash during the write operation. The difficulty exists because the actual ISR is buried in Arduino platform and bubbles up through HardwareTimer -> STM32_hwTimer -> TX handler, all of which has to be in RAM if it has any chance of working.

2021-04-20 23:20 UTC, JyeSmith approved these changes

2021-04-21 02:19 UTC, CapnBry commented
Some notes about the push I did. It looks like a lot but it is mostly removing like 4 variables, 2 function prototypes, and putting things into functions.

* Remove ExpressLRS_nextAirRate_* (except for index). The config class is enough to store this information until it is committed. 
  * Moved config class getters to header so they'll just get inlined where needed in IRAM callers
* syncSpamCounter is the only thing used now to track the spam sync. It just sets it to syncSpamAmount then counts down to 0 because we don't need to capture any of the other information from request to in progress.
* Rename HandleSyncSpam -> CheckConfigChangePending, and move the WaitEepromCommit code from loop into ConfigChangeCommit under that
* Move rename TimerCallbackISR and timerIdleCallback to timerCallbackNormal and timerCallbackIdle, moving them to where they don't need prototypes.

2021-04-21 07:00 UTC, JyeSmith commented
Tested again... still awesome!

LGTM

2021-04-21 18:08 UTC, CapnBry commented
I tested with your untested changes @AlessandroAU, and it didn't seem to be any better, but I liked where you were going with it so I spent all morning trying to get it to work. It seems simple enough but I just can not get it to work reliably, even if I disable the actual EEPROM commit and just wait 50ms by using your ``pause()`` function.

I tried making the timer wait until it was following the tock phase, I tried making it follow the tick phase, I tried making it follow the tick phase + 1/2 period and force a tock. I tried busywaiting during the last sync packet before fast forwarding. I mean, I tried a lot of different combinations and different ways of coming at the code while still making sure to not touch the radio while transmitting that last syncspam.

Two bugs:
1. **Affects all platforms** timerCallbackIdle only forwards the FHSSIdx, and does not update the radio, therefore, when it switches back to actually transmitting it is on the wrong frequency until the next hop. Remedy this by changing timerCallbackIdle() to call HandleFHSS() instead of just incrementing the index.
2. **STM32 platform only** You set isPaused = true the first time and never set it back to false anywhere so the second call to pause always returns immediately instead of phase-aligned like you'd expect.

I'm shocked at how much difficulty I've had getting this to work. I can get it to almost ok for short intervals, but there's a bunch of phase shift at the RX no matter what I do. At larger intervals (50ms) 500Hz gets out of sync by half a hop duration or more which causes it to stop getting sync packets and never will get caught up.

Unless you can make it work, I'd recommend fixing bug #1 above and pull out all the extra STM32 code and just ship it broken for STM32?

2021-04-21 21:28 UTC, CapnBry commented
Actually, I figured it out. What is happening is that when we call `setOverflow` in the hardware timer, it adjusts the prescaler register for the timer too, The prescaler change doesn't seem to take effect until the next overflow so when I say "Pause 20000us", the timer fires again 4735us later (which is 20000us using the old prescaler), where I set it back to the regular Rate Interval, and that one fires 16667us later (which is Rate Interval using my new prescaler). 

I can change this by locking the prescaler so that one tick is 1 us, which will give us up to 65535us of maximum timer per half-cycle. I am afraid this won't play nice with the sync offset though, which I believe wants to be able to adjust it much finer? Do we need sub-microsecond timing from HwTimer?

2021-04-22 01:56 UTC, CapnBry commented
I've pushed changes that work real good. Telemetry Ratio switches sync perfectly. Rate switches work about as well as you'd expect given the mechanism of the TX sending 3x packets at the old rate then switching, and the RX switching as soon as it gets one of them, which is to say pretty good but not perfect.

* Big one: On STM32 platform when changing parameters, the TX will now wait for the last SYNC packet to start going out, then figure out how many transmit cycles it expects would have been missed and set the timer to expire at the end of that period.
* Changed to not zero-out the telemetry ratio in the switch sync packets. It makes OpenTX say "Telemetry Lo-" "Telemetry Recovered" every time and there doesn't seem to be any practical benefit given how good our sync is. Tested down to 500Hz 1:2.
* The TX timer on STM32 has been changed to 1us resolution. RX is unchanged. This was needed to prevent having to change the prescaler and wait one overflow to actually change the timer. I think this is fine, because the RX should sync to the TX and the TX doesn't shift anyway.
* POWERMGNT has been changed to prevent changing power levels if it hasn't changed. I mean, why bother and waste time?
* I added the PRINT_RX_SCOREBOARD mode I've been using to the RX, it is super-helpful debugging and very lightweight. R=recv s=recv sync T=telem .=crc error _=nothing received

I think this works as well as anyone could hope for, I am done with it!

Giant glaring problem with all platforms:
The transmitter sends 3x sync packets then switches rate, the RX switches as soon as it gets a new rate in any of those sync packets. This is obviously a problem. I made the it fastforward using the NEW rate, since that may be closer to actuality and has at most `2 x (new - old)` cycles of error instead of compounding the error across the fastforward.

2021-04-22 07:21 UTC, AlessandroAU commented
Did some testing and it appears to work fine all major platforms

2021-04-22 07:21 UTC, merged