Add explicit unlock for telemetry data
ExpressLRS/ExpressLRS pull request #618
Opened 2021-05-17 19:47 UTC by schugabe

This PR fixes a bug that prevents sending of telemetry data if only one type of message is received from the FC.

Unlocking the old tlm message did happen in the same method that did fetch the next tlm message to be sent.
If no other type of tlm message is received the unlock step did always clear the update flag and prevented any further communication.

To fix this bug the Unlock/GetNextPayload is split in two methods. Now the current message is unlocked explicit after the sending is done.

After that a new message can be stored. The next call to GetNextPayload returns this message.

This issue would happen if betaflight is configured to send only the battery sensor.

2021-05-17 21:24 UTC, CapnBry requested changes
For everyone else's benefit, I'm the person that brought this bug up. To test it without the patch, just go to the betaflight CLI and disable all the sensors you can:
```
# Disable Attitude telemetry item
set telemetry_disabled_pitch = ON
set telemetry_disabled_roll = ON
set telemetry_disabled_heading = ON
# Disable Battery telemetry item
set telemetry_disabled_voltage = ON
set telemetry_disabled_current = ON
set telemetry_disabled_fuel = ON
# Disable GPS telemetry item
set telemetry_disabled_altitude = ON
set telemetry_disabled_lat_long = ON
set telemetry_disabled_ground_speed = ON
set telemetry_disabled_heading = ON
```
This will just leave the mode, which can't be disabled currently but I have a PR #10745 in to Betaflight to be able to turn it off in CRSF. After the first update to `FM`, it will stop updating and drop off. The Sender currently lets the FC add update telemetry, but when Telemetry class looks to see what to send, it was resetting the flags on the updated telemetry item because it though it just sent that one, but it was new!

This looks like it will fix it, and testing with just battery stats I see just them updating frequently. I think `GetCurrentPayload` should be removed before merging.

2021-05-17 21:24 UTC, CapnBry commented on src/lib/Telemetry/telemetry.cpp
>  uint8_t* Telemetry::GetCurrentPayload()
Can't we get rid of `GetCurrentPayload()`? Nothing else uses it and `UnlockCurrentPayload` already checks the lock. It doesn't do anything and just adds confusion. Just Unlock and move on in rx_main and eliminate GetCurrentPayload altogether. The pseudocode looks better I think
```
if (!Active)
    Unlock
    if (GetNext(&x))
        Sender.SetNext(x)
```
EDIT oops well I should have clicked a line at the end of the function so you could see it here, sorry about that.

2021-05-18 18:20 UTC, schugabe commented
I came up with a simpler solution: only reset lock+update flag if it entry was locked before. That does not change the usage of the class and fixes the issue. I also removed the unused method.

2021-05-18 18:37 UTC, CapnBry commented
Oh s**t yeah I like this a lot better, much easier to follow. I'll test this later today and approve if it passes testing. Looks like it will though.

2021-05-19 02:21 UTC, CapnBry approved these changes

2021-05-19 02:24 UTC, CapnBry commented
Yeah this is great, really nice refactor. It is easier to read than the first version and addresses the issue cleanly. Tested with Betaflight with 1x and 2x items, and my CRServoF servo outputter with just its one item. We'll see who will merge this in my sleep tonight for RC6.

2021-05-19 03:22 UTC, AlessandroAU commented
me! :)

2021-05-19 03:22 UTC, merged