Fix: STM32 build env setup cleanup to avoid mismatch with target names
ExpressLRS/ExpressLRS pull request #689
Opened 2021-06-16 06:01 UTC by cruwaller

2021-06-16 06:59 UTC, JyeSmith approved these changes

2021-06-16 07:06 UTC, wvarty approved these changes

2021-06-16 16:18 UTC, CapnBry requested changes
I'm not seeing any PostAction "buildprog" events firing at all on my builds, even after a clean+verbose. I see we have redundant `opentx.gen_elrs` calls so it seems the redundant calls should be removed or placed somewhere where they actually do something. See my comment in Discord #dev channel.

2021-06-16 18:22 UTC, CapnBry commented
Ok apparently buildprog does fire.

The redundant calls
```
        env.AddPostAction("buildprog", opentx.gen_elrs)
        env.AddPreAction("upload", opentx.gen_elrs)
```
Post buildprog is all we need since we only need to gen the elrs file if a new firmware has been built. No pre-upload action should be needed.

Finally, the "else" case now builds ELRS files for upload but then blindly sets the upload method to STLINK. "_STLINK" should have its own case in the if-train, or is the goal here to double-up the STLINK targets as also being the via_OPENTX target, then that should be made more clear via a comment.

2021-06-18 05:32 UTC, cruwaller commented
We have used `_STLINK` targets to build the `firmware.elrs` for handset flashing. This is old style and requires heap of work to change it. So, I am not going to make any actual workflow changes under this task. 
Point was to cleanup the old script to avoid conflicts with target names and make the script working as expected. 

... comments added.

2021-06-18 12:04 UTC, CapnBry approved these changes

2021-06-18 16:31 UTC, merged